apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd  
spec:
  generators:
  - git:
      directories:
      - path: overlays/*  
      repoURL: https://github.com/keer05/argocd.git  
      revision: kusto  
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}' 
    spec:
      project: default  
      source:
        repoURL: https://github.com/keer05/argocd.git 
        targetRevision: kusto 
        path: '{{path}}'  
        kustomize:
          namePrefix: my-app-  
      destination:
        server: https://kubernetes.default.svc
        namespace: ''
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true  
